### PR TITLE
Move property conversion so it's called on updates

### PR DESCRIPTION
**Pull request by jharwig**
If calling index.updateElement the conversion wasn't called so would fail if saving a BigDecimal or BigInteger

All tests use InMemoryElement which always calls `addElement`

### CODE REVIEW

**Comment by jharwig** [comment]
@joeferner  Should we change InMemoryElement to call updateElement for updates too?

**Comment by joeferner** [comment]
I'm a little surprised this isn't caught since the multi-module test will run Accumulo and ES plugins together. I think there are code paths we just must not be testing.

**Comment by sfeng88** [comment]
@jharwig can you add a changelog entry for this fix please?

**Comment by jharwig** [comment]
@sfeng88 done, also found a test that breaks before the fix. Needed to use `prepareMutation` to update an element not `prepareUpdate`

**Pull request merged**
